Repository locationtech/geotrellis, pull requests merged in 2019-10, with the labels that each got.

#3102 Fix Tiled TIFF BitCellType Segments conversion
  docs/CHANGELOG.rst
  raster/src/main/scala/geotrellis/raster/io/geotiff/GeoTiffSegment.scala
  raster/src/test/scala/geotrellis/raster/io/geotiff/BitGeoTiffTileSpec.scala
Labels: in progress

#3117 Rasters FeatureExtraction
  docs/CHANGELOG.rst
  raster/src/main/scala/geotrellis/raster/CellFeatures.scala
  raster/src/main/scala/geotrellis/raster/Implicits.scala
  raster/src/main/scala/geotrellis/raster/package.scala
  raster/src/test/scala/geotrellis/raster/CellFeaturesSpec.scala
Labels: needs review

#3131 Move CHANGELOG to Markdown format
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  README.md
  docs/CHANGELOG.rst
  docs/CONTRIBUTING.rst
  docs/CQ.rst
  docs/index.rst
Labels: documentation

#3138 Fix StreamingByteReader over-allocation past EOF
  .travis/build-and-test-set-1.sh
  CHANGELOG.md
  util/src/main/scala/geotrellis/util/StreamingByteReader.scala
Labels: bug
