Repository locationtech/geotrellis, pull requests merged in 2024-10, with the labels that each got.

#3542 potential fix for resamplemethod in reproject
  CHANGELOG.md
  raster/src/main/scala/geotrellis/raster/reproject/RasterRegionReproject.scala
  raster/src/test/scala/geotrellis/raster/reproject/ReprojectSpec.scala
Labels: bug

#3550 Resample code cleanup
  raster/src/main/scala/geotrellis/raster/reproject/RasterRegionReproject.scala
  raster/src/main/scala/geotrellis/raster/resample/Resample.scala
  raster/src/test/scala/geotrellis/raster/reproject/ReprojectSpec.scala
Labels: enhancement

#3482 Add union to merge methods
  CHANGELOG.md
  raster/src/main/scala/geotrellis/raster/merge/MultibandTileMergeMethods.scala
  raster/src/main/scala/geotrellis/raster/merge/RasterMergeMethods.scala
  raster/src/main/scala/geotrellis/raster/merge/RasterTileFeatureMergeMethods.scala
  raster/src/main/scala/geotrellis/raster/merge/SinglebandTileMergeMethods.scala
  raster/src/main/scala/geotrellis/raster/merge/TileFeatureMergeMethods.scala
  raster/src/main/scala/geotrellis/raster/merge/TileMergeMethods.scala
  raster/src/test/scala/geotrellis/raster/merge/TileUnionMethodsSpec.scala
Labels: enhancement

#3551 Dependencies update
  .github/workflows/ci.yml
  build.sbt
  project/Dependencies.scala
  project/Settings.scala
  project/build.properties
  project/plugins.sbt
Labels: dependencies, hacktoberfest-accepted

#3553 ConstantTile with NoData: support idempotent CellType conversions
  CHANGELOG.md
  project/build.properties
  raster/src/main/scala/geotrellis/raster/ConstantTile.scala
  raster/src/test/scala/geotrellis/raster/ConstantTileSpec.scala
Labels: bug
