Repository locationtech/geotrellis, pull requests merged in 2025-04, with the labels that each got.

#3570 set gdal roles for well known tags
  CHANGELOG.md
  raster/src/main/scala/geotrellis/raster/io/geotiff/Tags.scala
  raster/src/test/scala/geotrellis/raster/io/geotiff/writer/GeoTiffWriterSpec.scala
Labels: enhancement

#3572 Avoid GeoAttrsError by using more robust target extent calculation
  CHANGELOG.md
  spark/src/main/scala/geotrellis/spark/reproject/TileRDDReproject.scala
  spark/src/test/scala/geotrellis/spark/reproject/TileRDDReprojectSpec.scala
Labels: bug

#3573 ReprojectRasterExtent: support single pixel input
  CHANGELOG.md
  raster/src/main/scala/geotrellis/raster/reproject/ReprojectRasterExtent.scala
  raster/src/test/scala/geotrellis/raster/reproject/ReprojectRasterExtentSpec.scala
Labels: bug

#3574 Dependencies update
  .github/docker-compose.yml
  .github/docker/gdal/3.x/ubuntu/Dockerfile
  .github/workflows/ci.yml
  build.sbt
  project/Dependencies.scala
  project/Settings.scala
  project/build.properties
  project/plugins.sbt
Labels: needs cq
